# Exposes ports for debugging
version: '3'
services:
  db:
    platform: linux/x86_64
    image: 'mysql:8'
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "4000:3306"
  backend:
    image: backend:latest
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db
  ui:
    image: ui:latest
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
volumes:
  db-volume:
