version: '3'
services:
  db:
    platform: linux/x86_64
    image: 'db:latest'
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    restart: on-failure
  app:
    image: app:latest
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms128m -Xmx512m
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:8080"
      - "443:8080"
    volumes:
      - app-volume:/data
    restart: on-failure
volumes:
  db-volume:
  app-volume:
