# Exposes ports for debugging
version: '3'
services:
  db:
    platform: linux/x86_64
    image: 'db:latest'
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    image: app:latest
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -Xms128m -Xmx512m
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8080"
      - "8000:8000"
    volumes:
      - app-volume:/data
    depends_on:
      - db
volumes:
  db-volume:
  app-volume:
