plugins {
    id 'org.springframework.boot' version '2.5.6'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'checkstyle'
}

group = 'com.ksonni'
version = '0.0.1'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:2.6.3'
    implementation 'org.springframework.boot:spring-boot-starter-validation:2.6.3'
    implementation 'org.springframework.boot:spring-boot-starter-security:2.6.3'
    implementation 'org.springframework.boot:spring-boot-starter-web:2.6.3'
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'org.projectlombok:lombok:1.18.36'
    implementation 'org.liquibase:liquibase-core:4.7.1'
    implementation 'org.mapstruct:mapstruct:1.4.2.Final'
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.5'
    implementation 'com.github.vladimir-bukhtoyarov:bucket4j-core:7.1.0'
    implementation 'org.apache.tika:tika-core:2.2.1'

    runtimeOnly 'mysql:mysql-connector-java:8.0.26'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.6.3'
    testImplementation 'org.springframework.security:spring-security-test:5.5.1'
    testImplementation 'org.mockito:mockito-core:4.3.1'

    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed', 'standardError'
        exceptionFormat = 'full'
    }
}

jar {
    enabled = false
}

springBoot {
    buildInfo()
}

checkstyle {
    toolVersion '8.40'
}
