# App
app.max-requests-per-min=60
app.files-path=/data/files/
app.file-size-limit-bytes=512000

# Server
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/certificates/football-db.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.enabled=true
server.error.include-message=always
server.error.whitelabel.enabled=false
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

# Docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.validatorUrl=none
spring.graphql.graphiql.enabled=true

# Misc
spring.liquibase.changeLog=classpath:/db/migrations/change-log.xml
