plugins {
    id 'java'
    id 'checkstyle'

    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.deps)
    alias(libs.plugins.graphql.codegen)
}

group = 'com.ksonni'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
    }
}

repositories {
    mavenCentral()
}

configurations {
    mockitoAgent
}

dependencies {
    implementation libs.spring.data
    implementation libs.spring.validation
    implementation libs.spring.security
    implementation libs.spring.web
    implementation libs.spring.openapi
    implementation libs.spring.graphql

    implementation libs.lombok
    implementation libs.mapstruct

    implementation libs.liquibase
    runtimeOnly libs.mysql

    implementation libs.apache.http
    implementation libs.apache.tika
    implementation libs.bucket4j

    testImplementation libs.spring.test
    testImplementation libs.spring.graphql.test
    testImplementation libs.webflux
    testImplementation libs.spring.security.test

    testImplementation libs.mockito
    mockitoAgent(libs.mockito) {
        transitive = false
    }

    annotationProcessor libs.lombok
    annotationProcessor libs.mapstruct.processor
    annotationProcessor libs.mapstruct.binding
}

def graphqlOutDir = "${layout.buildDirectory.get()}/generated/sources/graphql"

graphqlCodegen {
    graphqlSchemas.includePattern = "schema\\.graphqls"
    packageName = "com.ksonni.footballdb.generated.ql"
    outputDir = new File(graphqlOutDir)
    generateApis = false
    modelNamePrefix = "QL"
    generatedAnnotation = "jakarta.annotation.Generated"
    modelValidationAnnotation = "jakarta.validation.constraints.NotNull"
}
compileJava.dependsOn 'graphqlCodegen'
sourceSets.main.java.srcDir graphqlOutDir

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed', 'standardError'
        exceptionFormat = 'full'
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}

jar {
    enabled = false
}

springBoot {
    buildInfo()
}

checkstyle {
    toolVersion libs.versions.checkstyle.get()
}
