plugins {
    id 'java'
    id 'checkstyle'

    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDeps)
}

group = 'com.ksonni'
version = '0.0.1'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.get().toInteger()))
    }
}

repositories {
    mavenCentral()
}

configurations {
    mockitoAgent
}

dependencies {
    implementation(libs.springData)
    implementation(libs.springValidation)
    implementation(libs.springSecurity)
    implementation(libs.springWeb)
    implementation(libs.springOpenApi)

    implementation(libs.lombok)
    implementation(libs.mapstruct)

    implementation(libs.liquibase)
    runtimeOnly(libs.mysql)

    implementation(libs.apacheHttp)
    implementation(libs.apacheTika)
    implementation(libs.bucket4j)

    testImplementation(libs.springTest)
    testImplementation(libs.springSecurityTest)

    testImplementation(libs.mockito)
    mockitoAgent(libs.mockito) {
        transitive = false
    }

    annotationProcessor(libs.lombok)
    annotationProcessor(libs.mapstructProcessor)
    annotationProcessor(libs.mapstructBinding)
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed', 'standardError'
        exceptionFormat = 'full'
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}

jar {
    enabled = false
}

springBoot {
    buildInfo()
}

checkstyle {
    toolVersion libs.versions.checkstyle.get()
}
