type Query {}

input IntFilter {
    eq: Int
    ne: Int
    lt: Int
    lte: Int
    gt: Int
    gte: Int
}

input StringFilter {
    eq: String
    ne: String
    contains: String
}

enum SortDirection {
    ASC,
    DESC,
}

input Sort {
    priority: Int = 0,
    direction: SortDirection = ASC,
}

input Pagination {
    page: Int = 0,
    size: Int = 20,
}

scalar DateTime

input DateTimeFilter {
    eq: DateTime
    ne: DateTime
    lt: DateTime
    lte: DateTime
    gt: DateTime
    gte: DateTime
}